### ISSUE TITLE
[FR]: Skip Forced Login

### ISSUE THREAD

**Issue by DarkCrypt** [devaryakjha/varanasi_mobile_app#79]
I installed this app and noticed a forced login in order to use it.

Can you add an option to use the app without an account?

**Comment by devaryakjha** [comment]
@DarkCrypt yeah sure, I'll add this in the next update.

**Comment by DarkCrypt** [comment]
Awesome! I'm looking forward to try out this app.

**Comment by DarkCrypt** [comment]
Thank you for your quick reply and implementation! Users will appreciate the choice.

I've been trying out the app and it works great. I'm excited to watch this app grow with future features. Keep up the good work friend, God bless!
